general.import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
#normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
#normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 10

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.85

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
